name: Backend pipeline

on:
  push:
    branches:
      - main
  pull_request:
      branches: [master]
      types: [opened, synchronize]

jobs:
  test-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install backend
        working-directory: ./backend
        run: npm install
      - name: test backend
        working-directory: ./backend
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          SECRET: ${{secrets.SECRET}}
        run: npm run test