name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  backend-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: cd backend && npm install
#      - name: test
#        run: cd backend && npm run test
      - name: environments
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI}}
        run: echo "$MONGODB_URI"